### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by qiujunhan** [WaterArchery/LitSellChest#4]
Players can buy multiple boxes, but due to permission issues, they spend money but cannot use the boxes. They hope that this can be checked at the time of purchase.
If a player does not have permission to place a chest or if the maximum quantity has been reached, the chest will become invalid after being placed and can no longer be used.

**Comment by WaterArchery** [comment]
The only convenient way that I think of is showing the maximum placeable and the current chests in the shop GUI. Now, you can use %playerLimit% and %playerCount% placeholders in the shop menu.
